export default {
  BUILD_BOARD: 'BUILD_BOARD',
  POPULATE_ENTITIES: 'POPULATE_ENTITIES',
  TOGGLE_VALUE: 'TOGGLE_VALUE',
  NEXT_TICK: 'NEXT_TICK',
  PLAY_GAME: 'PLAY_GAME',
  PAUSE_GAME: 'PAUSE_GAME'
};

